;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env]

platform = espressif32
board = esp32cam
framework = arduino

; Serial Monitor options
monitor_speed = 115200

lib_deps =
# Using library Name
    IRremoteESP8266
    Adafruit NeoPixel
    ArduinoJson @ ~6.19.4
    PubSubClient
    EEPROM
    DHT sensor library
    Adafruit Unified Sensor

build_flags =
    -D CORE_DEBUG_LEVEL=5
    -D MQTT_MAX_PACKET_SIZE=512
    -D MQTT_KEEPALIVE=5
    -D ARDUINOJSON_USE_LONG_LONG=1
    -include flash_info.h
;    !python3 -c "import os; print('-D STATIC_CONFIG_ACTIVE' if os.path.isfile('static_config.h') else '')"

extra_scripts =
    pre:generate_extra_info.py
;    pre:generate_static_config.py

build_src_filter =
    +<*>
    -<system/*>

[env:neopixel_only_static_config]

build_flags =
    -D SINGLE_NEOPIXEL
    !python3 -c "import os; print('-D STATIC_CONFIG_ACTIVE' if os.path.isfile('static_config.h') else '')"

extra_scripts =
    pre:generate_static_config.py

[env:neopixel_only]

build_flags =
    -D SINGLE_NEOPIXEL
