#pragma once
// This file is auto-generated by 'export_enums.py' in 'https://github.com/johannesgrothe/Smarthome_Bridge'

// A number identifier for every gadget type
enum class GadgetIdentifier {
    err_type = 0,
    lamp_neopixel_basic = 1,
    lamp_basic = 2,
    fan_westinghouse_ir = 3,
    lamp_westinghouse_ir = 4,
    doorbell_basic = 5,
    wallswitch_basic = 6,
    sensor_motion_hr501 = 7,
    sensor_temperature_dht = 8
};

// Count of the values in GadgetIdentifier
//#define GadgetIdentifierCount 8
constexpr int GadgetIdentifierCount = 8;

// A number identifier for every characteristic type
enum class CharacteristicIdentifier {
    err_type = 0,
    status = 1,
    fan_speed = 2,
    brightness = 3,
    hue = 4,
    saturation = 5,
    temperature = 6,
    humidity = 7
};

// Count of the values in CharacteristicIdentifier
#define CharacteristicIdentifierCount 7
