name: Bug Report
description: File a bug report
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what you did and what happened.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-should-have-happened
    attributes:
      label: What should have happened?
      description: Tell us, what you expected the system to do.
      placeholder: Tell us what you wanted to see!
      value: "Everything worked!"
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical do you believe the bug to be?
      options:
        - Kinda Irrelevant
        - Annoying (Default)
        - Pretty Severe
        - Perror das Errortier
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: reproducability
    attributes:
      label: Reproducability
      description: Is this bug reproducable?
      options:
        - label: Check if bug is reproducable
