name: Repository Checks

on: [ pull_request ]

jobs:
  semi_linear_history_check:

    name: Check Semi-Linear History

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check Semi-Linear History
        run: git merge-base --is-ancestor origin/develop HEAD

  submodule_master_check:

    name: System Submodule is on master

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check if submodule is on master
        uses: jtmullen/submodule-branch-check-action@v1
        with:
          path: "src/system"
          branch: "master"

  submodule_most_recent_master_check:

    name: System Submodule is on most recent master

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check if submodule is on most recent master commit
        uses: jtmullen/submodule-branch-check-action@v1
        with:
          path: "src/system"
          branch: "master"
          require_head: true
