name: Submodule Branch Checks

on: [ pull_request ]

jobs:
  build:

    name: Check Submodule Branch Status

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check if Submodules are on master
        uses: jtmullen/submodule-branch-check-action@v1
        with:
          path: "src/system"
          branch: "master"
          require_head: true
